default:
  image: php:7
  services:
  - mysql:5.7
  artifacts:
    untracked: true
    paths:
    - bin
    - vendor
    - var

variables:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_USER: tests
  MYSQL_PASSWORD: tests
  MYSQL_DATABASE: app
  DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE?serverVersion=5.7"

stages:
- build_yarn
- build_sf
- build_assets
- tests
- run

yarn_install:
  stage: build_yarn
  image: 20minutes/node-12-yarn-serverless
  script:
  - yarn install --dev

sf_vendors:
  stage: build_sf
  image: composer:1.9
  script:
  - composer install -n

sf_assets:
  stage: build_assets
  image: 20minutes/node-12-yarn-serverless
  script:
  - yarn encore dev
  - yarn encore production
