name: build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install --dev
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Build Assets
      run: |
        yarn encore dev
        yarn encore production
    - name: Create artifact
      run: tar -zcvf artifact.tar.gz vendor bin node_modules assets var
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: demo-app
        path: .

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: demo-app
    - name: Restore artifact
      run: tar -zxvf artifact.tar.gz && rm artifact.tar.gz
    - name: Unit tests
      run: php bin/phpunit ./tests/unit-tests
    - name: Functional tests
      run: php bin/phpunit ./tests/functionnal-tests
